common/models/Sales.php
<?php

namespace common\models;

use common\models\Queries\SalesQuery;
use frontend\components\Lang;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "sales".
 *
 * @property int $id
 * @property int $sale_type
 * @property int $status_id
 * @property int $start_at
 * @property int $due_to
 * @property int $category_id
 * @property float $value
 * @property int $value_type
 * @property int $created_at
 * @property-read SaleProducts[] $products
 * @property-read SalesInfo $info
 * @property-read SaleParticipants[] $participants
 * @property-read Categories $category
 * @property-read mixed $imagesLinks
 * @property-read ImageManager[] $images
 * @property-read mixed $imagesLinksData
 * @property-read ImageManager $image
 * @property int $updated_at
 */
class Sales extends ActiveRecord
{
    // Sale statuses
    const STATUS_ACTIVE = 1;
    const STATUS_PAUSED = 2;
    const STATUS_DELETED = 3;
    const STATUS_ARCHIVED = 4;

    // Discount types
    const TYPE_UAH = 1;
    const TYPE_PERCENT = 2;

    /**
     * @return SalesQuery
     */
    public static function get()
    {
        return self::find()->joinWith(['products', 'participants', 'category'])->orderBy('created_at DESC');
    }

    /**
     * {@inheritdoc}
     * @return SalesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SalesQuery(get_called_class());
    }

    public static function getIds()
    {
        return self::find()->select('id')->orderBy('id DESC')->one();
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['sale_type', 'status_id', 'start_at', 'due_to', 'category_id', 'value', 'value_type'], 'required'],
            [['sale_type', 'status_id', 'start_at', 'due_to', 'category_id', 'value_type', 'created_at', 'updated_at'], 'integer'],
            [['value'], 'number'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sale_type' => 'Sale Type',
            'status_id' => 'Status ID',
            'start_at' => 'Start At',
            'due_to' => 'Due To',
            'category_id' => 'Category ID',
            'value' => 'Value',
            'value_type' => 'Value Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getInfo()
    {
        if (!SalesInfo::find()->where(['record_id' => $this->id, 'lang' => Lang::getCurrentId()])->cache(3600 * 5)->exists())
            return $this->hasOne(SalesInfo::className(), ['record_id' => 'id'])->andWhere(['lang' => 1])->cache(3600 * 5);

        return $this->hasOne(SalesInfo::className(), ['record_id' => 'id'])->andWhere(['lang' => Lang::getCurrentId()])->cache(3600 * 5);
    }

    /**
     * @return ActiveQuery
     */
    public function getParticipants()
    {
        return $this->hasMany(SaleParticipants::className(), ['sale_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(SaleProducts::className(), ['sale_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }

    public function getImage()
    {
        return $this->hasOne(ImageManager::className(), ['record_id' => 'id'])->andWhere(['module' => self::tableName()])->orderBy('sort');
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sales';
    }

    public function getImagesLinks()
    {
        return ArrayHelper::getColumn($this->images, 'imageUrl');
    }

    public function getImagesLinksData()
    {
        return ArrayHelper::toArray($this->images, [
                ImageManager::className() => [
                    'caption' => 'path',
                    'key' => 'id',
                ]]
        );
    }

    public function beforeDelete()
    {
        if ($this->getImages()) {
            foreach ($this->images as $one) {
                @unlink(Yii::getAlias('@images') . '/' . self::tableName() . '/' . $one->path);
            }
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getImages()
    {
        return $this->hasMany(ImageManager::className(), ['record_id' => 'id'])->andWhere(['module' => self::tableName()])->orderBy('sort');
    }
}

frontend/controllers/SalesController.php
<?php


namespace frontend\controllers;


use common\models\Sales;
use Yii;
use yii\web\NotFoundHttpException;

class SalesController extends BaseController
{
    public function actionIndex()
    {
        return $this->render('index', [
            'sales' => Sales::find()->limit(Yii::$app->request->queryParams['limit'] ?: 12)->orderBy('created_at DESC')->all(),
        ]);
    }

    public function actionView($id)
    {
        $sale = Sales::findOne($id);
        if (!$sale)
            throw new NotFoundHttpException();

        return $this->render('view', [
            'sale' => $sale,
        ]);
    }
}

frontend/views/sales/index.php
<?php

use frontend\widgets\Breadcrumbs;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $sales \common\models\Sales[] */

$this->title = Yii::t('app', 'Акции');

$breadcrumbs = [];
$breadcrumbs[] = ['label' => $this->title, 'url' => '#'];

$sale_indexes = [[], [], []];

$data_indexes = [0, 1, 2];
foreach ($sales as $key => $sale) {
    $cur_index = array_shift($data_indexes);
    $sale_indexes[$cur_index][] = $key;

    $data_indexes[] = $cur_index;
}
?>

<main>
    <div class="container">
        <div class="prev-link">
            <?= Breadcrumbs::widget(['links' => $breadcrumbs]) ?>
        </div>
        <div class="blog">
            <div class="title">
                <div class="title__line"></div>
                <div class="title__text"><?= Html::encode($this->title) ?><span></span></div>
            </div>
            <div class="blog__body mobail">
                <?php foreach ($sales as $sale): ?>
                    <a class="blog-cart" href="<?= Url::to(['/sales/view', 'id' => $sale->id]) ?>">
                        <div class="blog-cart__fake"><img alt="" src="<?= $sale->image->imageUrl ?>"></div>
                        <div class="blog-cart__body">
                            <div class="blog-cart__img"><img alt="" src="<?= $sale->image->imageUrl ?>">
                                <div class="blog-cart__hashtag">
                                    <div class="blog-cart__hashtag__example">
                                        #<?= Html::encode($sale->info->label_name) ?></div>
                                </div>
                                <div class="blog-cart__watch">
                                    <img alt="" src="/assets/img/product-cart/watch.svg"><span>233</span></div>
                                <div class="blog-cart__text">
                                    <?= Html::encode($sale->info->name) ?>
                                </div>
                            </div>
                            <div class="blog-cart__link">
                                <p><?= Yii::t('app', 'Читать далее') ?></p>
                                <span><img alt="" src="/assets/img/icon/arow_to.svg"></span>
                            </div>
                        </div>
                    </a>
                <?php endforeach; ?>
            </div>
            <div class="blog__body">
                <?php foreach ($sale_indexes as $column__index): ?>
                    <div class="blog__column">
                        <?php foreach ($column__index as $sale__index): ?>
                            <a class="blog-cart" href="<?= Url::to(['/sales/view', 'id' => $sale->id]) ?>">
                                <div class="blog-cart__fake"><img alt="" src="<?= $sales[$sale__index]->image->imageUrl ?>"></div>
                                <div class="blog-cart__body">
                                    <div class="blog-cart__img"><img alt="" src="<?= $sales[$sale__index]->image->imageUrl ?>">
                                        <div class="blog-cart__hashtag">
                                            <div class="blog-cart__hashtag__example">#<?= Html::encode($sales[$sale__index]->info->label_name) ?></div>
                                        </div>
                                        <div class="blog-cart__watch">
                                            <img alt="" src="/assets/img/product-cart/watch.svg"><span>233</span>
                                        </div>
                                        <div class="blog-cart__text">
                                            <?= Html::encode($sales[$sale__index]->info->name) ?>
                                        </div>
                                    </div>
                                    <div class="blog-cart__link">
                                        <p><?= Yii::t('app', 'Читать далее') ?></p>
                                        <span><img alt="" src="/assets/img/icon/arow_to.svg"></span>
                                    </div>
                                </div>
                            </a>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="paginations">
            <div class="paginations__page"><span>30</span>из<span>300</span>статей</div>
            <a class="more-link hover-button" href="#">
                <div class="hover-button__front"><span>Еще 30 статей</span></div>
                <div class="hover-button__back"><span>Еще 30 статей</span></div>
            </a>
            <ul class="paginations__menu">
                <li class="paginations__item"><a class="paginations__link active" href="#">1</a></li>
                <li class="paginations__item"><a class="paginations__link" href="#">2</a></li>
                <li class="paginations__item"><a class="paginations__link" href="#">3</a></li>
                <li class="paginations__item more"><a class="paginations__link" href="#">...</a></li>
                <li class="paginations__item"><a class="paginations__link" href="#">10</a></li>
            </ul>
        </div>
        <?= $this->render('//site/descriptFemail') ?>
    </div>
</main>

frontend/views/sales/view.php
<?php

/* @var $this \yii\web\View */
/* @var $sale \common\models\Sales */

use frontend\widgets\Breadcrumbs;
use yii\helpers\Html;

$this->title = $sale->info->name;

$breadcrumbs = [];
$breadcrumbs[] = ['label' => Yii::t('app', 'Акции'), 'url' => ['/sales/index']];
$breadcrumbs[] = ['label' => $this->title, 'url' => '#'];
?>

<div class="container">
    <div class="prev-link">
        <?= Breadcrumbs::widget(['links' => $breadcrumbs]) ?>
    </div>
    <div class="blog-example">
        <div class="blog-example__container">
            <div class="title">
                <div class="title__line"></div>
                <div class="title__text">
                    <?= Html::encode($this->title) ?>
                    <span></span>
                </div>
            </div>
            <div class="blog-slider-item__img"><img alt="" src="<?= $sale->image->imageUrl ?>">
                <div class="blog-slider-item__hashtag">
<!--                    <div class="blog-slider-item__hashtag__example">#Бренды</div>-->
                </div>
                <div class="blog-slider-item__post-week">пост недели</div>
            </div>
            <div class="blog-example__text">
                <?= Html::encode($sale->info->comment) ?>
            </div>
        </div>
    </div>
</div>