common/models/Bag.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "bag".
 *
 * @property int $id
 * @property int $user_id
 * @property int $product_id
 * @property Products $product
 * @property int $quantity
 * @property int $size
 * @property-read ProductParamsValues $colorData
 * @property int $color
 */
class Bag extends \yii\db\ActiveRecord
{
    /**
     * @param int $user_id
     * @return string
     */
    public static function renderBagProducts($user_id)
    {
        if (!Yii::$app->user->isGuest)
            $bag_products = self::getUserBag($user_id);
        else
            $bag_products = Yii::$app->session->get('bag') ?: [];

        return Yii::$app->controller->renderPartial('//includes/_bag', ['bag_products' => $bag_products]);
    }

    /**
     * @param $user_id
     * @return Bag[]
     */
    public static function getUserBag($user_id)
    {
        return self::find()->joinWith(['product', 'product.image'])->where(['user_id' => $user_id])->all();
    }

    /**
     * @param int $user_id
     * @return bool
     */
    public static function bagHasProducts($user_id)
    {
        return self::find()->where(['user_id' => $user_id])->exists();
    }

    /**
     * Get bag products grouped by brands
     * @param $user_id
     * @return Brands[]
     */
    public static function getByBrands($user_id)
    {
        return Brands::find()->joinWith(['products.bag', 'products.image'])->andWhere([Bag::tableName() . '.user_id' => \Yii::$app->user->getId()])->all();
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bag';
    }

    /**
     * @param $user_id
     * @return int
     */
    public static function clearUserBag($user_id)
    {
        return self::deleteAll(['user_id' => $user_id]);
    }

    /**
     * @return bool
     */
    public static function saveFromSession()
    {
        if (Yii::$app->user->isGuest || !Yii::$app->session->has('bag'))
            return false;

        $bag = Yii::$app->session->get('bag');
        foreach ($bag as $item) {
            $item->user_id = Yii::$app->user->getId();
            $item->save();
        }

        Yii::$app->session->remove('bag');

        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'product_id'], 'required'],
            [['user_id', 'product_id', 'quantity', 'size', 'color'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'product_id' => 'Product ID',
            'quantity' => 'Quantity',
        ];
    }

    public function loadAttrs($data)
    {
        $this->user_id = Yii::$app->user->getId() ?: 0;

        $this->setAttributes($data, false);

        return true;
    }

    /**
     * @return bool
     */
    public function saveBag()
    {
        if (!Yii::$app->user->isGuest) {
            if (self::find()->where(['user_id' => $this->user_id, 'product_id' => $this->product_id, 'size' => $this->size, 'color' => $this->color])->exists()) {
                self::updateAllCounters(['quantity' => 1], ['user_id' => $this->user_id, 'product_id' => $this->product_id, 'size' => $this->size, 'color' => $this->color]);
                return true;
            }
            return $this->save();
        }

        $session = Yii::$app->session;
        if (!$session->has('bag'))
            $session->set('bag', []);

        $bag = $session->get('bag');
        if (!isset($bag[$this->product_id])) {
            $bag[$this->product_id] = $this;

            $session->set('bag', $bag);
        }

        return true;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Products::className(), ['id' => 'product_id'])->cache(3600 * 24)->orderBy('`brand_id` ASC');
    }

    /**
     * Remove a product from the bag
     * @return int
     */
    public function remove()
    {
        return self::deleteAll(['user_id' => $this->user_id, 'id' => $this->product_id]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getColorData()
    {
        return $this->hasOne(ProductParamsValues::className(), ['id' => 'color']);
    }
}

frontend/controllers/BagController.php
<?php


namespace frontend\controllers;


use common\models\Bag;
use common\models\Brands;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Response;

class BagController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'add-product' => ['post'],
                    'remove-product' => ['post'],
                    'remove-bag-product' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (in_array($action->id, ['add-product', 'remove-product'])) {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        $this->layout = 'order';

        if (!Bag::bagHasProducts(\Yii::$app->user->getId()) || \Yii::$app->user->isGuest)
            return $this->redirect(\Yii::$app->request->referrer ?: ['/']);


        return $this->render('index', [
            'bag' => Bag::getByBrands(\Yii::$app->user->getId()),
        ]);
    }

    public function actionAddProduct()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $model = new Bag();

        if ($model->loadAttrs(\Yii::$app->request->post()) && $model->validate() && $model->saveBag())
            return ['status' => 'success', 'products' => Bag::renderBagProducts($model->user_id)];

        return ['status' => 'error'];
    }

    public function actionRemoveProduct()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $model = new Bag();

        if ($model->loadAttrs(\Yii::$app->request->post()) && $model->validate() && $model->remove())
            return ['status' => 'success', 'products' => Bag::renderBagProducts($model->user_id)];

        return ['status' => 'error'];
    }

    public function actionRemoveBagProduct()
    {
        $model = new Bag();

        if ($model->loadAttrs(\Yii::$app->request->get()) && $model->validate())
            $model->remove();

        return $this->redirect(\Yii::$app->request->referrer ?: ['/']);
    }
}

frontend/views/bag/index.php
<?php

/* @var $this \yii\web\View */

use common\models\Orders;
use frontend\components\Helper;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $bag \common\models\Brands[] */

$count_bag = count($bag);

$this->title = Yii::t('app', 'Корзина');
?>

<div class="container-fluid">
    <div class="container">
        <div class="bag-page">
            <div class="bag-page__title">
                <div class="title">
                    <div class="title__line"></div>
                    <div class="title__text"><?= Yii::t('app', 'Корзина') ?><span></span></div>
                </div>
                <?php if ($count_bag > 1): ?>
                    <div class="bag-page__title__text">
                        <div>i</div>
                        <span><?= Yii::t('app', 'Внимание') ?>!</span>
                        <p><?= Yii::t('app', 'Товары от разных продавцов оформляются отдельно, ваш заказ разделен на {0} части', $count_bag) ?></p>
                    </div>
                <?php endif; ?>
            </div>
            <div class="bag-page__body">
                <?php $order_num = 1; $order_id = Orders::getNewOrderNum(); $order_full_sum = 0; $order_discount_sum = 0; ?>
                <?php foreach ($bag as $bag_item): ?>
                    <div class="bag-page-order <?= $order_num == $count_bag ? 'last' : '' ?>">
                        <div class="bag-page-order__title">
                            <?= Yii::t('app', 'Заказ') . ' ' . $order_num ?>
                            <span>(№<?= $order_id ?>)</span>
                        </div>
                        <div class="bag-page-order__body">
                            <div class="bag-page-order__container">
                                <div class="bag-page-order__menu">
                                    <div class="bag-page-order__value"><?= Yii::t('app', 'Товар') ?></div>
                                    <div class="bag-page-order__value"><?= Yii::t('app', 'Количество') ?></div>
                                    <div class="bag-page-order__value"><?= Yii::t('app', 'Цена') ?></div>
                                </div>
                                <div class="bag-page-order__fake"></div>
                            </div>
                            <div class="bag-page-order__infornation">
                                <div class="bag-page-order__order">
                                    <?php foreach ($bag_item->products as $product): ?>
                                        <?php if (!$product->bag) continue; ?>

                                        <?php foreach ($product->bag as $product_bag): ?>
                                            <div class="product-bag-page">
                                                <div class="product-bag-page__body">
                                                    <?= Html::a('', ['/bag/remove-bag-product', 'product_id' => $product_bag->id, 'quantity' => 1], [
                                                        'class' => 'product-bag-page__close',
                                                        'data' => [
                                                            'confirm' => Yii::t('app', 'Вы уверены что хотите удалить этот товар?'),
                                                            'method' => 'post',
                                                        ],
                                                    ]) ?>
                                                    <div class="product-bag-page__img"><img
                                                                alt="" src="<?= $product->image->imageUrl ?>"></div>
                                                    <div class="product-bag-page__information">
                                                        <div class="product-bag-page__name"><?= $product->info->name ?></div>
                                                        <div class="product-bag-page__number">№ <?= Helper::formatNumber($product->id) ?></div>
                                                        <div class="product-bag-page__size">
                                                            <p><?= Yii::t('app', 'Размер') ?> (UKR): </p><span><?= $product->bag[0]->size ?></span>
                                                        </div>
                                                        <div class="product-bag-page__color blue">
                                                            <p><?= Yii::t('app', 'Цвет') ?></p>
                                                            <div style="background-color: <?= $product_bag->colorData->additional_value ?>;"></div>
                                                            <span><?= $product_bag->colorData->value ?></span>
                                                        </div>
                                                    </div>
                                                    <div class="product-bag-page__counter">
                                                        <div class="product-bag-page__remove">-</div>
                                                        <div class="product-bag-page__value"><?= $product_bag->quantity ?></div>
                                                        <div class="product-bag-page__add">+</div>
                                                    </div>
                                                    <div class="product-bag-page__cost">
                                                        <?= Helper::formatPrice($product->price * $product_bag->quantity) ?> грн
                                                        <?php if ($product->discount): ?>
                                                            <div class="product-bag-page__promo">
                                                                <?= Yii::t('app', 'c промокодом {0} грн', Helper::formatPrice($product->discountPrice * $product_bag->quantity)) ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <?php $order_full_sum += ($product->price * $product_bag->quantity); $order_discount_sum += ($product->discountPrice * $product_bag->quantity); ?>
                                        <?php endforeach; ?>

                                    <?php endforeach; ?>
                                </div>
                                <div class="bag-page-order__cost">
                                    <div class="bag-page-order__text__container">
                                        <div class="bag-page-order__text">
                                            <p><?= Yii::t('app', 'Продавец') ?>:</p><span><?= $bag_item->name ?></span>
                                        </div>
                                        <div class="bag-page-order__text">
                                            <p><?= Yii::t('app', 'Итого к оплате') ?>:</p><span><?= Helper::formatPrice($order_full_sum) ?> грн</span>
                                            <?php if ($order_full_sum > $order_discount_sum): ?>
                                                <div class="bag-page-order__promo"><?= Yii::t('app', 'c промокодом {0} грн', $order_discount_sum) ?></div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                $order_discount_sum = 0; $order_full_sum = 0;
                $order_num++;
                $order_id++;
                endforeach;
                ?>
                <div class="bag-page-order__bg">
                    <a href="<?= Url::to(['/order/index']) ?>" class="bag-page-order__btn hover-button">
                        <div class="hover-button__front"><span><?= Yii::t('app', 'Оформить заказ') ?></span></div>
                        <div class="hover-button__back"><span><?= Yii::t('app', 'Оформить заказ') ?></span></div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>